config/routes.rb
GraphDemo::Application.routes.draw do
  root :to => 'questions#redirect', via: :get
  match '/q', to: 'questions#index', as: :questions, via: :get
  match '/q', to: 'questions#create', as: '', via: :post
  match '/q/new(.:format)', to: 'questions#create', as: '', via: :post
  match '/q/new(.:format)', to: 'questions#new', as: :new_question, via: :get
  match '/q/:id/edit(.:format)', to: 'questions#edit', as: :edit_question, via: :get
  match '/q/:id(.:format)', to: 'questions#show', as: :question, via: :get
  match '/q/:id(.:format)', to: 'questions#update', via: [:patch, :put]
  match '/q/:id(.:format)', to: 'questions#destroy', via: :delete
  match '/q/increment/:id/:q', to: 'questions#increment', :via => [:get], as: :increment
  match '/q/stream/:id', to: 'questions#stream', :via => [:get], as: :stream
  match '/q/get_status/:id', to: 'questions#get_status', :via => [:get], as: :get_status
  match '/q/s/:id', to: 'questions#streaming_graph', :via => [:get], as: :streaming_graph

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include ActionController::Live

  before_action :set_question, only: [:stream, :get_status, :show, :streaming_graph, :edit, :update, :destroy, :increment]

  def redirect
    redirect_to action: :show, id: 1
  end

  def stream
    response.headers['Content-Type'] = 'text/event-stream'

    300.times do |i|
      ActiveRecord::Base.connection_pool.with_connection do
        Question.uncached do
          set_question
        end
      end

      response.stream.write("event: message\n")
      response.stream.write("data: #{create_json_response.to_json}\n\n")
      sleep 1
    end

    response.stream.write("event: done\n")
    response.stream.write("data: done\n\n")
  ensure
    response.stream.close
  end

  def get_status
      render json: create_json_response.to_json
  end
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  def stream_show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  def increment
    @question.increment!(params[:q])
    render json: create_json_response, status: 200
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :q_1, :q_1_count, :q_2, :q_2_count, :q_3, :q_3_count, :q_4, :q_4_count)
    end

    def create_json_response
      [
        {label: @question.q_1, value: @question.q_1_count},
        {label: @question.q_2, value: @question.q_2_count},
        {label: @question.q_3, value: @question.q_3_count},
        {label: @question.q_4, value: @question.q_4_count},
      ]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GraphDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :q_1 %><br>
    <%= f.text_field :q_1 %>
  </div>
  <div class="field">
    <%= f.label :q_1_count %><br>
    <%= f.number_field :q_1_count %>
  </div>
  <div class="field">
    <%= f.label :q_2 %><br>
    <%= f.text_field :q_2 %>
  </div>
  <div class="field">
    <%= f.label :q_2_count %><br>
    <%= f.number_field :q_2_count %>
  </div>
  <div class="field">
    <%= f.label :q_3 %><br>
    <%= f.text_field :q_3 %>
  </div>
  <div class="field">
    <%= f.label :q_3_count %><br>
    <%= f.number_field :q_3_count %>
  </div>
  <div class="field">
    <%= f.label :q_4 %><br>
    <%= f.text_field :q_4 %>
  </div>
  <div class="field">
    <%= f.label :q_4_count %><br>
    <%= f.number_field :q_4_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/increment.js.erb
exec_d3();

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Q 1</th>
      <th>Q 1 count</th>
      <th>Q 2</th>
      <th>Q 2 count</th>
      <th>Q 3</th>
      <th>Q 3 count</th>
      <th>Q 4</th>
      <th>Q 4 count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.q_1 %></td>
        <td><%= question.q_1_count %></td>
        <td><%= question.q_2 %></td>
        <td><%= question.q_2_count %></td>
        <td><%= question.q_3 %></td>
        <td><%= question.q_3_count %></td>
        <td><%= question.q_4 %></td>
        <td><%= question.q_4_count %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p class="title"><%= @question.title %></p>
<div id="wrapper">
  <div id="chart-container"></div>

<%= javascript_tag do %>
    var chart = {};
    chart.isInit = true;

    chart.container = document.getElementById('chart-container');
    chart.margin = {top:20, right:20, bottom:30, left:50};
    chart.barPadding = 0.4;

    chart.width = chart.container.clientWidth - chart.margin.left - chart.margin.right;
    chart.height = chart.container.clientHeight - chart.margin.top - chart.margin.bottom;

    chart.scaleX = d3.scale.ordinal().rangeRoundBands([0, chart.width], chart.barPadding);
    chart.scaleY = d3.scale.linear().range([chart.height, 0]);

    chart.xAxis = d3.svg.axis()
      .scale(chart.scaleX)
      .orient('bottom')
      .innerTickSize(0)
      .outerTickSize(0)
      .tickPadding(15);
    chart.yAxis = d3.svg.axis()
      .scale(chart.scaleY)
      .orient('left')
      .innerTickSize(-chart.width)
      .outerTickSize(0)
      .tickPadding(10);

    chart.colors = ['#d64a4c', '#eca634', '#84aa64', '#4eb7d5', '#dc874e', '#a4a634', '#8caaac', '#6cc9fc'];
    chart.tween = {duration:500};

    chart.svg = d3.select('#chart-container').append('svg')
      .attr('width', chart.width + chart.margin.left + chart.margin.right)
      .attr('height', chart.height + chart.margin.top + chart.margin.bottom)
      .append('g')
        .attr('class', 'wrapper')
        .attr('transform', 'translate(' + chart.margin.left + ',' + chart.margin.top + ')');

    chart.svg.append('g').attr('class', 'axis');
    chart.svg.append('g').attr('class', 'bars');

    //** Draw chart
    chart.draw = function(data) {
      chart.scaleX.domain(data.map(function(d) { return d.label}));
      chart.scaleY.domain([0, d3.max(data, function(d) { return d.value})]);

      var bar = chart.svg.select('.bars').selectAll('.bar').data(data);
      bar.enter().append('rect')
        .attr('class', 'bar')
        .attr('fill', function(d, i) { return chart.colors[i];})
        .attr('x', function(d) { return (chart.isInit)? chart.scaleX(d.label) : chart.width;})
        .attr('width', chart.scaleX.rangeBand())
        .attr('y', chart.height)
        .attr('height', 0)
        .transition().duration(chart.tween.duration)
          .attr('x', function(d) { return chart.scaleX(d.label);})
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .attr('height', function(d) { return chart.height - chart.scaleY(d.value);});
      bar.exit()
        .transition().duration(chart.tween.duration)
          .attr('x', chart.width)
          .attr('y', chart.height)
          .attr('height', 0)
          .remove();

      var value = chart.svg.select('.bars').selectAll('.value').data(data);
      value.enter().append('text')
        .attr('class', 'value')
        .attr('text-anchor', 'middle')
        .attr('x', function(d) { return (chart.isInit)? (chart.scaleX.rangeBand() / 2) + chart.scaleX(d.label) : chart.width; })
        .attr('y', chart.height)
        .attr('dy', '1em')
        .style('opacity', 0)
        .text(0)
        .transition().duration(chart.tween.duration)
          .tween('text', function(d) {
            return chart.tweeningValue(this, d.value);
          })
          .attr("x", function(d) { return (chart.scaleX.rangeBand() / 2) + chart.scaleX(d.label); })
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .style('opacity', 1);
      value.exit()
        .transition().duration(chart.tween.duration)
          .attr('x', chart.width)
          .attr('y', chart.height)
          .style('opacity', 0)
          .remove();

      if(chart.isInit) {
        chart.svg.select('.axis').append('g')
          .attr('class', 'x')
          .attr('transform', 'translate(0,' + chart.height + ')')
          .call(chart.xAxis);
        chart.svg.select('.axis').append('g')
          .attr('class', 'y')
          .call(chart.yAxis);

        chart.isInit = false;
      } else {
        bar.transition().duration(chart.tween.duration)
          .attr('x', function(d) { return chart.scaleX(d.label);})
          .attr('width', chart.scaleX.rangeBand())
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .attr('height', function(d) { return chart.height - chart.scaleY(d.value);});

        value.transition().duration(chart.tween.duration)
          .tween('text', function(d) {
            return chart.tweeningValue(this, d.value);
          })
          .attr("x", function(d) { return (chart.scaleX.rangeBand() / 2) + chart.scaleX(d.label); })
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .style('opacity', 1);

        chart.svg.selectAll('g.axis .x').transition().call(chart.xAxis);
        chart.svg.selectAll('g.axis .y').transition().call(chart.yAxis);
      }
    }

    //** Tweening value
    chart.tweeningValue = function(t, d) {
      var i = d3.interpolate(t.textContent, d);
      var prec = (d + '').split('.');
      var round = (prec.length > 1) ? Math.pow(10, prec[1].length) : 1;
      return function(n) {
        t.textContent = Math.round(i(n) * round) / round;
      }
    }

    var exec_d3 = function() {
      d3.json('<%= get_status_path %>', function(err, res) {
        setTimeout(function() {
          chart.draw(res);
        }, 500);
      });
    }

    exec_d3();
<% end %>

<div id="console">
  <div class="row">
    <div class="vote">
      <p><%= link_to '投票する', increment_path(q: 'q_1_count'), remote: true %></p>
      <p><%= link_to '投票する', increment_path(q: 'q_2_count'), remote: true %></p>
      <p><%= link_to '投票する', increment_path(q: 'q_3_count'), remote: true %></p>
      <p><%= link_to '投票する', increment_path(q: 'q_4_count'), remote: true %></p>
    </div>
  </div>

  <div class="row btn reload" onclick="exec_d3();">
    <a href="javascript:void(0)">グラフを再取得する</a>
  </div>
</div>
</div>
<%= javascript_include_tag 'questions' %>

app/views/questions/streaming_graph.html.erb
<p class="title"><%= @question.title %></p>
<div id="wrapper">
  <div id="chart-container"></div>

<%= javascript_tag do %>
    var chart = {};
    chart.isInit = true;

    chart.container = document.getElementById('chart-container');
    chart.margin = {top:20, right:20, bottom:30, left:50};
    chart.barPadding = 0.4;

    chart.width = chart.container.clientWidth - chart.margin.left - chart.margin.right;
    chart.height = chart.container.clientHeight - chart.margin.top - chart.margin.bottom;

    chart.scaleX = d3.scale.ordinal().rangeRoundBands([0, chart.width], chart.barPadding);
    chart.scaleY = d3.scale.linear().range([chart.height, 0]);

    chart.xAxis = d3.svg.axis()
      .scale(chart.scaleX)
      .orient('bottom')
      .innerTickSize(0)
      .outerTickSize(0)
      .tickPadding(15);
    chart.yAxis = d3.svg.axis()
      .scale(chart.scaleY)
      .orient('left')
      .innerTickSize(-chart.width)
      .outerTickSize(0)
      .tickPadding(10);

    chart.colors = ['#d64a4c', '#eca634', '#84aa64', '#4eb7d5', '#dc874e', '#a4a634', '#8caaac', '#6cc9fc'];
    chart.tween = {duration:500};

    chart.svg = d3.select('#chart-container').append('svg')
      .attr('width', chart.width + chart.margin.left + chart.margin.right)
      .attr('height', chart.height + chart.margin.top + chart.margin.bottom)
      .append('g')
        .attr('class', 'wrapper')
        .attr('transform', 'translate(' + chart.margin.left + ',' + chart.margin.top + ')');

    chart.svg.append('g').attr('class', 'axis');
    chart.svg.append('g').attr('class', 'bars');

    //** Draw chart
    chart.draw = function(data) {
      chart.scaleX.domain(data.map(function(d) { return d.label}));
      chart.scaleY.domain([0, d3.max(data, function(d) { return d.value})]);

      var bar = chart.svg.select('.bars').selectAll('.bar').data(data);
      bar.enter().append('rect')
        .attr('class', 'bar')
        .attr('fill', function(d, i) { return chart.colors[i];})
        .attr('x', function(d) { return (chart.isInit)? chart.scaleX(d.label) : chart.width;})
        .attr('width', chart.scaleX.rangeBand())
        .attr('y', chart.height)
        .attr('height', 0)
        .transition().duration(chart.tween.duration)
          .attr('x', function(d) { return chart.scaleX(d.label);})
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .attr('height', function(d) { return chart.height - chart.scaleY(d.value);});
      bar.exit()
        .transition().duration(chart.tween.duration)
          .attr('x', chart.width)
          .attr('y', chart.height)
          .attr('height', 0)
          .remove();

      var value = chart.svg.select('.bars').selectAll('.value').data(data);
      value.enter().append('text')
        .attr('class', 'value')
        .attr('text-anchor', 'middle')
        .attr('x', function(d) { return (chart.isInit)? (chart.scaleX.rangeBand() / 2) + chart.scaleX(d.label) : chart.width; })
        .attr('y', chart.height)
        .attr('dy', '1em')
        .style('opacity', 0)
        .text(0)
        .transition().duration(chart.tween.duration)
          .tween('text', function(d) {
            return chart.tweeningValue(this, d.value);
          })
          .attr("x", function(d) { return (chart.scaleX.rangeBand() / 2) + chart.scaleX(d.label); })
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .style('opacity', 1);
      value.exit()
        .transition().duration(chart.tween.duration)
          .attr('x', chart.width)
          .attr('y', chart.height)
          .style('opacity', 0)
          .remove();

      if(chart.isInit) {
        chart.svg.select('.axis').append('g')
          .attr('class', 'x')
          .attr('transform', 'translate(0,' + chart.height + ')')
          .call(chart.xAxis);
        chart.svg.select('.axis').append('g')
          .attr('class', 'y')
          .call(chart.yAxis);

        chart.isInit = false;
      } else {
        bar.transition().duration(chart.tween.duration)
          .attr('x', function(d) { return chart.scaleX(d.label);})
          .attr('width', chart.scaleX.rangeBand())
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .attr('height', function(d) { return chart.height - chart.scaleY(d.value);});

        value.transition().duration(chart.tween.duration)
          .tween('text', function(d) {
            return chart.tweeningValue(this, d.value);
          })
          .attr("x", function(d) { return (chart.scaleX.rangeBand() / 2) + chart.scaleX(d.label); })
          .attr('y', function(d) { return chart.scaleY(d.value);})
          .style('opacity', 1);

        chart.svg.selectAll('g.axis .x').transition().call(chart.xAxis);
        chart.svg.selectAll('g.axis .y').transition().call(chart.yAxis);
      }
    }

    //** Tweening value
    chart.tweeningValue = function(t, d) {
      var i = d3.interpolate(t.textContent, d);
      var prec = (d + '').split('.');
      var round = (prec.length > 1) ? Math.pow(10, prec[1].length) : 1;
      return function(n) {
        t.textContent = Math.round(i(n) * round) / round;
      }
    }

    $(function() {
        var eventSource = new EventSource("<%= stream_path %>");

        eventSource.addEventListener("message", function(event) {
            message = $.parseJSON(event.data);
            chart.draw(message);
        });
        eventSource.addEventListener("done", function(event) {
            this.close();
            window.location.reload();
        });
    });
<% end %>

<div id="console">
  <div class="row">
    <div class="vote">
      <p><%= link_to '投票する', increment_path(q: 'q_1_count'), remote: true %></p>
      <p><%= link_to '投票する', increment_path(q: 'q_2_count'), remote: true %></p>
      <p><%= link_to '投票する', increment_path(q: 'q_3_count'), remote: true %></p>
      <p><%= link_to '投票する', increment_path(q: 'q_4_count'), remote: true %></p>
    </div>
  </div>

  <div class="row btn">
    <%= link_to 'Edit', edit_question_path(@question) %> |
    <%= link_to 'Back', questions_path %>
  </div>
</div>
</div>